[mypy]
ignore_missing_imports = True

[mypy-src.application.use_cases.process_webhook_use_case]
ignore_errors = True

[mypy-src.infrastructure.database.models]
ignore_errors = True

[mypy-src.infrastructure.database.repositories.client_repository]
ignore_errors = True

[mypy-src.infrastructure.database.repositories.event_repository]
ignore_errors = True
